version: '3'

services:
  db:
    build: './db'
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
    expose:
      - "3307"
  web:
    depends_on:
      - db
    build: '.'
    ports:
      - "3000:3000"
    command: >
      bash -c "
        chmod u+x ./wait-for-it.sh && 
        ./wait-for-it.sh db:3306 &&
        npm install -g db-migrate &&
        npm install -g db-migrate-mysql &&
        db-migrate up &&
        npm start
      "
  