version: '3'

services:
  test_db:
    container_name: test_db
    image: 'mysql:5.7'
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=customer_api_database_test
    tmpfs: /var/lib/mysql

  db:
    image: 'mysql:5.7'
    container_name: db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=customer_api_database
    volumes: 
      - customers-db:/var/lib/mysql
  backend:
    container_name: backend
    depends_on:
      - db
    build: '.'
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=customer_api_database
      - DB_HOST=db
      - DB_PORT=3306
    ports:
      - "5000:5000"
    command: 'bash -c "chmod u+x ./wait-for-it.sh && ./wait-for-it.sh db:3306 && npm run start:watch"'
  
volumes:
  customers-db: