name: Integration tests MySQL
on:
  pull_request:
    branches: [master, dev]
jobs: 
  setup-db:
    runs-on: 'ubuntu-18.04'
    container:
      image: 'mysql:5.7'
      env:
        - MYSQL_USER=tester
        - MYSQL_PASSWORD=WildWildPass
        - MYSQL_RANDOM_ROOT_PASSWORD=yes
        - MYSQL_DATABASE=customer_api_database_test
      options: --mount type=tmpfs,destination=/var/lib/mysql
  run-tests: 
    runs-on: 'ubuntu-18.04'
    needs: setup-db
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm i -g db-migrate db-migrate-mysql
      - run: DB_HOST=localhost DB_PORT=3306 DB_USER=tester DB_PASS=WildWildPass DB_NAME=customer_api_database_test db-migrate up
      - run: npm test
        env:
          CI: true
          PORT: 3001
          DB_DIALECT: mysql
          DB_HOST_TEST: localhost
          DB_USER_TEST: tester
          DB_PASS_TEST: WildWildPass
          DB_NAME_TEST: customer_api_database_test
          DB_PORT_TEST: 3306
