name: Integration tests MySQL
on:
  pull_request:
    branches: [master, dev]
jobs: 
  test: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306 # Optional, default value is 3306. The port of host
          container port: 3306 # Optional, default value is 3306. The port of container
          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mysql version: '5.7' # Optional, default value is "latest". The version of the MySQL
          mysql database: 'customer_api_database_test' # Optional, default value is "test". The specified database which will be create
          mysql root password: 'root' # Required if "mysql user" is empty, default is empty. The root superuser password
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm i -g db-migrate db-migrate-mysql
      - run: npm run tests:migrate-db
      - run: npm test
        env:
          CI: true
          PORT: 3001
          DB_DIALECT: mysql
          DB_HOST_TEST: localhost
          DB_USER_TEST: root
          DB_PASS_TEST: root
          DB_NAME_TEST: customer_api_database_test
          DB_PORT_TEST: 3306
